default:
  image: ghcr.io/prefix-dev/pixi:0.76.1

stages:
  - verify

verify:
  stage: verify
  before_script:
    - apt-get update -qq
    - apt-get install -y --no-install-recommends git
  script:
    - pixi run check
    - pixi run eval-synthetic
  cache:
    key:
      files:
        - pixi.lock
    paths:
      - .pixi
