name: ebnerd
variant: large
language: da
archive_url: https://ebnerd-dataset.s3.eu-west-1.amazonaws.com/ebnerd_large.zip
archive: ebnerd_large.zip
test_archive_url: https://ebnerd-dataset.s3.eu-west-1.amazonaws.com/ebnerd_testset.zip
test_archive: ebnerd_testset.zip
availability: published_at
validation_days: 1
