name: ebnerd
variant: large
language: da
archive_url: https://ebnerd-dataset.s3.eu-west-1.amazonaws.com/ebnerd_large.zip
archive: ebnerd_large.zip
articles_archive_url: https://ebnerd-dataset.s3.eu-west-1.amazonaws.com/articles_large_only.zip
articles_archive: articles_large_only.zip
test_archive_url: https://ebnerd-dataset.s3.eu-west-1.amazonaws.com/ebnerd_testset.zip
test_archive: ebnerd_testset.zip
embedding_archive_url: https://ebnerd-dataset.s3.eu-west-1.amazonaws.com/artifacts/google_bert_base_multilingual_cased.zip
embedding_archive: google_bert_base_multilingual_cased.zip
embedding_path: data/raw/ebnerd/large/embeddings/bert
embedding_source: bert
availability: published_at
validation_days: 1
